Repository micronaut-projects/micronaut-jaxrs, pull requests merged in 2020-09, with the labels that each got.

#53 [jaxrs] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#59 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#61 [jaxrs] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#63 checkstyle: unused import
  jaxrs-processor/src/main/java/io/micronaut/jaxrs/processor/GetAnnotationMapper.java
Labels: type: improvement

#66 ci: bump up to micronaut docs 1.0.24
  gradle.properties
Labels: relates-to: build

#67 ci: del micronautBuildVersion
  gradle.properties
Labels: relates-to: build
