Repository micronaut-projects/micronaut-jaxrs, pull requests merged in 2022-02, with the labels that each got.

#187 logback classic to ch.qos.logback:logback-classic:1.2.10
  examples/example-jdbc/build.gradle
Labels: type: dependency-upgrade

#195 Support for JAX-RS Exception
  jaxrs-server/build.gradle
  jaxrs-server/src/main/java/io/micronaut/jaxrs/runtime/core/JaxRsExceptionHandler.java
  jaxrs-server/src/test/java/io/micronaut/jaxrs/runtime/NotificationClient.java
  jaxrs-server/src/test/java/io/micronaut/jaxrs/runtime/NotificationsResource.java
  jaxrs-server/src/test/java/io/micronaut/jaxrs/runtime/ResponseTest.java
Labels: type: enhancement

#194 [jaxrs] Update common files for branch master
  .github/workflows/release-notes.yml
  .github/workflows/sonarqube.yml
  README.md
  build.gradle
Labels: relates-to: build
