Repository micronaut-projects/micronaut-jaxrs, pull requests merged in 2023-08, with the labels that each got.

#338 docs: Remove unnecessary version numbers
  src/main/docs/guide/quickStart.adoc
  src/main/docs/guide/supportedApi.adoc
Labels: type: docs

#336 [jaxrs] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#341 getHeaderString was returning an empty string for missing headers
  jaxrs-server/src/main/java/io/micronaut/jaxrs/runtime/ext/bind/JaxRsHttpHeaders.java
  jaxrs-server/src/test/java/io/micronaut/jaxrs/runtime/HeadersResource.java
  jaxrs-server/src/test/java/io/micronaut/jaxrs/runtime/HeadersTest.java
Labels: type: bug

#342 Add support for resolveTemplate and resolveTemplates
  jaxrs-server/src/main/java/io/micronaut/jaxrs/runtime/core/JaxRsUriBuilder.java
  jaxrs-server/src/test/groovy/io/micronaut/jaxrs/runtime/core/JaxRsUriBuilderSpec.groovy
Labels: type: improvement
